# Generated by Django 4.2.3 on 2023-07-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='like_count',
        ),
    ]
