# Generated by Django 4.2.3 on 2023-07-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_product_comment_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=75)),
                ('heading1', models.CharField(default='', max_length=100)),
                ('cheading1', models.CharField(default='', max_length=5000)),
                ('heading2', models.CharField(default='', max_length=100)),
                ('cheading2', models.CharField(default='', max_length=5000)),
                ('heading3', models.CharField(default='', max_length=1000)),
                ('cheading3', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='myapp/images/blog')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField(default='')),
                ('desc', models.TextField(default='')),
            ],
        ),
    ]
