# Generated by Django 4.2.3 on 2023-07-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_product_likes_product_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
